(source "elpy" "http://jorgenschaefer.github.io/packages/")
(source "gnu" "http://elpa.gnu.org/packages/")
(source "marmalade" "http://marmalade-repo.org/packages/")
(source "melpa" "https://stable.melpa.org/packages/")

(depends-on "ac-helm")
(depends-on "adoc-mode")
(depends-on "ag")
(depends-on "ansible")
(depends-on "ansible-doc")
(depends-on "anzu")
(depends-on "auto-complete")
(depends-on "avy")
(depends-on "benchmark-init")
(depends-on "bm")
(depends-on "calfw")
(depends-on "calfw-gcal")
(depends-on "cask")
(depends-on "circe")
(depends-on "couette" :git "https://github.com/blallau/couette")
(depends-on "counsel")
(depends-on "counsel-projectile")
(depends-on "counsel-tramp")
(depends-on "dim")
(depends-on "dired-narrow")
(depends-on "dired-quick-sort")
(depends-on "dired-ranger")
(depends-on "dired-subtree")
(depends-on "docker")
(depends-on "docker-tramp")
(depends-on "dockerfile-mode")
(depends-on "dropbox")
(depends-on "elfeed")
(depends-on "elisp-slime-nav")
(depends-on "epc")
(depends-on "eruby-mode" :git "https://github.com/petere/emacs-eruby-mode")
(depends-on "es-mode")
(depends-on "fancy-narrow")
(depends-on "fic-mode")
(depends-on "find-file-in-repository")
(depends-on "flycheck")
(depends-on "flymake-ruby")
(depends-on "frame-cmds")
(depends-on "git-gutter")
(depends-on "git-link")
;(depends-on "git-messenger")
(depends-on "git-timemachine")
(depends-on "go-autocomplete")
(depends-on "go-eldoc")
(depends-on "go-mode")
(depends-on "go-projectile")
;(depends-on "golden-ratio")
(depends-on "image+")
(depends-on "indent-tools" :git "https://gitlab.com/emacs-stuff/indent-tools.git")
(depends-on "ini-mode")
(depends-on "helm")
(depends-on "helm-descbinds")
(depends-on "helm-git-grep")
(depends-on "helm-projectile")
(depends-on "helm-swoop")
(depends-on "htmlize")
(depends-on "image+")
(depends-on "iedit")
(depends-on "jedi")
(depends-on "jinja2-mode")
(depends-on "json-mode")
(depends-on "logview" :git "https://github.com/doublep/logview")
(depends-on "lua-mode")
(depends-on "magit")
(depends-on "magit-filenotify")
(depends-on "magit-review" :git "https://github.com/blallau/magit-review")
(depends-on "magithub")
(depends-on "nginx-mode")
(depends-on "ob-go")
(depends-on "nginx-mode")
(depends-on "ob-go")
(depends-on "nginx-mode")
(depends-on "ob-go")
(depends-on "nginx-mode")
(depends-on "ob-go")
(depends-on "markdown-mode")
(depends-on "markdown-mode+")
(depends-on "markdown-toc")
(depends-on "moe-theme")
(depends-on "multi-term")
(depends-on "ob-go")
(depends-on "multiple-cursors")
(depends-on "ob-http")
(depends-on "ox-rst")
(depends-on "ox-rst")
(depends-on "ob-ipython")
(depends-on "ob-restclient")
(depends-on "org-cliplink")
(depends-on "pcap-mode")
(depends-on "pcap-mode")
(depends-on "pcap-mode")
(depends-on "pcap-mode")
(depends-on "org-download")
(depends-on "org-pdfview")
(depends-on "org-gcal")
(depends-on "org-projectile")
(depends-on "ox-asciidoc")
(depends-on "ox-reveal")
(depends-on "padawan" :git "https://github.com/blallau/padawan")
(depends-on "pallet")
(depends-on "peep-dired")
(depends-on "persistent-scratch")
(depends-on "pip-requirements")
(depends-on "pkg-info")
(depends-on "popup")
(depends-on "projectile")
;(depends-on "puml-mode")
(depends-on "puppet-mode" :git "https://github.com/smoeding/puppet-syntax-emacs")
(depends-on "python-environment")
(depends-on "salt-mode")
(depends-on "rainbow-delimiters")
(depends-on "rainbow-mode")
(depends-on "terraform-mode")
(depends-on "restclient")
(depends-on "robe")
(depends-on "vlf")
(depends-on "stacktest" :git "https://github.com/sdague/stacktest")
;(depends-on "swiper" :git "https://github.com/abo-abo/swiper")
(depends-on "swiper-helm" :git "https://github.com/abo-abo/swiper-helm")
(depends-on "undo-tree")
(depends-on "use-package")
(depends-on "weather-metno")
(depends-on "which-key")
(depends-on "wttrin")
(depends-on "yaml-mode")
(depends-on "yarn-mode")
