(source "elpy" "http://jorgenschaefer.github.io/packages/")
(source "gnu" "http://elpa.gnu.org/packages/")
(source "marmalade" "http://marmalade-repo.org/packages/")
(source "melpa" "http://melpa.milkbox.net/packages/")

(depends-on "ac-helm")
(depends-on "adoc-mode")
(depends-on "ansible")
(depends-on "ansible-doc")
(depends-on "anzu")
(depends-on "auto-complete")
(depends-on "benchmark-init")
(depends-on "cask")
(depends-on "circe")
(depends-on "couette" :git "https://github.com/blallau/couette")
(depends-on "dim")
(depends-on "dropbox")
(depends-on "elfeed")
(depends-on "elisp-slime-nav")
(depends-on "epc")
(depends-on "fancy-narrow")
(depends-on "fic-mode")
(depends-on "flycheck")
(depends-on "git-gutter")
(depends-on "git-messenger")
(depends-on "git-timemachine")
(depends-on "helm")
(depends-on "helm-descbinds")
(depends-on "helm-git-grep")
(depends-on "helm-projectile")
(depends-on "helm-swoop")
(depends-on "htmlize")
(depends-on "iedit")
(depends-on "jedi")
(depends-on "jinja2-mode")
(depends-on "magit")
(depends-on "magit-filenotify")
(depends-on "magit-review" :git "https://github.com/blallau/magit-review")
(depends-on "markdown-mode")
(depends-on "markdown-mode+")
(depends-on "markdown-toc")
(depends-on "moe-theme")
(depends-on "multi-term")
(depends-on "ob-http")
(depends-on "ob-ipython")
(depends-on "ob-restclient")
(depends-on "org-download")
(depends-on "org-mode-jira")
(depends-on "org-projectile")
(depends-on "ox-reveal")
(depends-on "padawan" :git "https://github.com/blallau/padawan")
(depends-on "pallet")
(depends-on "pip-requirements")
(depends-on "pkg-info")
(depends-on "popup")
(depends-on "projectile")
(depends-on "python-environment")
(depends-on "rainbow-delimiters")
(depends-on "rainbow-mode")
(depends-on "restclient")
(depends-on "stacktest" :git "https://github.com/sdague/stacktest")
(depends-on "swiper" :git "https://github.com/abo-abo/swiper")
(depends-on "swiper-helm" :git "https://github.com/abo-abo/swiper-helm")
(depends-on "undo-tree")
(depends-on "use-package")
(depends-on "which-key")
(depends-on "yaml-mode")
(depends-on "yasnippet")
