;; Highlight matching parenthesis (useful when coding)
(require 'paren)
(show-paren-mode t)
(setq blink-matching-paren t)
(setq blink-matching-paren-on-screen t)
(setq show-paren-style 'mixed)
(setq blink-matching-paren-dont-ignore-comments t)
